#!/usr/bin/env node
'use strict';
/**
 * lint.js — the cheapest check that earns its place: every script parses, every config is JSON.
 * No dependency, no style rules, nothing to argue about. It is here so CI has something to fail on
 * from the first commit rather than after the first outage.
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = path.join(__dirname, '..');
let checked = 0;
const problems = [];

// site/data/*.json (allowances, claims, funding, treasury) are all generated by the scripts in
// scripts/, and checked in so a fresh clone has something to read before any of them have run —
// this just re-parses whatever is there. config/addresses.json is the one scripts/chain.js reads
// and site/config/addresses.json is its twin for the site and the serverless functions; both are
// checked, and neither is required to match the other, though today they do.
const JS_DIRS = ['scripts', 'site', 'site/api', 'site/api/lib', 'site/api/lib/providers', 'site/api/lib/payers', 'test', 'test/support', 'test/site', 'test/site/support'];
const JSON_DIRS = ['config', 'site/config', 'site/data'];

// Nothing in this tree is loaded as an ES module today — MODULE_JS exists for the day one is,
// so Node's syntax checker is told to parse it as a module rather than misreading its import
// statements as a syntax error.
const MODULE_JS = new Set([]);

for (const dir of JS_DIRS) {
  const full = path.join(root, dir);
  if (!fs.existsSync(full)) continue;
  for (const name of fs.readdirSync(full)) {
    if (!name.endsWith('.js')) continue;
    const rel = `${dir}/${name}`;
    const file = path.join(full, name);
    const args = MODULE_JS.has(rel) ? ['--input-type=module', '--check'] : ['--check', file];
    try {
      if (MODULE_JS.has(rel)) execFileSync(process.execPath, args, { input: fs.readFileSync(file), stdio: 'pipe' });
      else execFileSync(process.execPath, args, { stdio: 'pipe' });
      checked++;
    } catch (e) { problems.push(`${rel}: ${String(e.stderr || e).split('\n').slice(0, 2).join(' ')}`); }
  }
}
for (const dir of JSON_DIRS) {
  const full = path.join(root, dir);
  if (!fs.existsSync(full)) continue;
  for (const name of fs.readdirSync(full)) {
    if (!name.endsWith('.json')) continue;
    try { JSON.parse(fs.readFileSync(path.join(full, name), 'utf8')); checked++; }
    catch (e) { problems.push(`${dir}/${name}: ${e.message}`); }
  }
}

// The scripts read config/addresses.json and the site reads site/config/addresses.json, and the
// duplication is deliberate — the deploy ships only site/, so it cannot reach up out of it. What
// was missing was anything to notice them drifting apart, which would have the keepers and the
// page quietly working against different contracts or different RPC endpoints. Byte-for-byte,
// because a difference in either direction is a mistake and neither copy is the authority.
const ADDR_PAIR = ['config/addresses.json', 'site/config/addresses.json'];
const addrFiles = ADDR_PAIR.map((rel) => path.join(root, rel));
if (addrFiles.every((f) => fs.existsSync(f))) {
  const [a, b] = addrFiles.map((f) => fs.readFileSync(f, 'utf8'));
  if (a !== b) problems.push(`${ADDR_PAIR[0]} and ${ADDR_PAIR[1]} have drifted apart; they are meant to be identical copies`);
  else checked++;
} else {
  problems.push(`one of ${ADDR_PAIR.join(' / ')} is missing; both are meant to exist`);
}

if (problems.length) { problems.forEach((p) => console.error('  ' + p)); console.error(`lint: ${problems.length} problem(s)`); process.exit(1); }
console.log(`lint: ${checked} file(s) OK (syntax and config JSON only — no style rules, no new dependency)`);
